import { ServerContext } from "@/app/_components/server-context"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ServerContext.Provider value="Hello from Server Context!">
        {children}
        </ServerContext.Provider>
        </body>
    </html>
  )
}
